# Generated by Django 4.2.9 on 2024-02-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pm',
        ),
        migrations.AddField(
            model_name='post',
            name='am_pm',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='PM', max_length=2, verbose_name='AM/PM'),
        ),
        migrations.AlterField(
            model_name='post',
            name='day_of_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1, verbose_name='Day'),
        ),
    ]
