# Generated by Django 4.2.9 on 2024-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0002_remove_post_pm_post_am_pm_alter_post_day_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='need_to_change_month',
            field=models.BooleanField(default=False, verbose_name='Next month'),
        ),
    ]
