# Generated by Django 4.2.9 on 2024-02-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0003_post_need_to_change_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='need_to_change_month',
            new_name='next_month',
        ),
    ]
