# Generated by Django 4.2.9 on 2024-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0004_rename_need_to_change_month_post_next_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selenium',
            field=models.CharField(default='', max_length=100, verbose_name='Selenium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webdriver',
            field=models.CharField(default='', max_length=255, verbose_name='Webdriver'),
        ),
    ]
