# Generated by Django 4.2.9 on 2024-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0005_alter_profile_selenium_alter_profile_webdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selenium',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Selenium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webdriver',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Webdriver'),
        ),
    ]
