# Generated by Django 4.2.9 on 2024-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0006_alter_profile_selenium_alter_profile_webdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_12_plus',
            field=models.BooleanField(default=False, verbose_name='Is 12+'),
        ),
    ]
