# Generated by Django 4.2.9 on 2024-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0007_post_is_12_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_clear_posts_folder',
            field=models.BooleanField(default=False, verbose_name='Need clear posts folder'),
        ),
    ]
