# Generated by Django 4.2.9 on 2024-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0008_profile_need_clear_posts_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
