# Generated by Django 4.2.9 on 2024-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapa', '0011_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='subscribers',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Subscribers'),
        ),
    ]
